### ISSUE TITLE
Embedded Browser Not Displaying

### ISSUE THREAD

**Issue by KoryMac** [danieloneill/TwitchOverlay#15]
I built your program using QtCreator, and as far as I can tell, after some adjustments to my compositor and setting an exception for this application, it works. However, what I imagine is meant to be an embedded browser window when I click "Link Twitch Account", does not work. All I get is a white screen. Do you know why this is? I can try to fix this on my own, but am not really sure where to start. I'd really like to use your program, because twitch overlays for Linux are surprisingly hard to find. Either way, thanks for writing this. If I manage to get it working on my own, I'll mention what I changed.

**Comment by danieloneill** [comment]
Chances are you don't have Qt WebEngine libraries installed.

**Comment by kevinkjt2000** [comment]
This blank white web browser was happening to me too. I was missing the qt-multimedia package (qt6-multimedia on the Arch Linux box I use). Output looked like this before I added it:
```
❯ ./TwitchOverlay
qrc:/qml/main.qml:20:5: Type Chatter unavailable
         Chatter {
         ^
qrc:/qml/Chatter.qml:5:1: module "QtMultimedia" is not installed
     import QtMultimedia        // Qt 6.x
     ^
Done positioning, resetting window flags!
qrc:/qml/configure.qml:94:9: Type StylePreview unavailable
             StylePreview {
             ^
qrc:/qml/StylePreview.qml:32:5: Type Chatter unavailable
         Chatter {
         ^
qrc:/qml/Chatter.qml:5:1: module "QtMultimedia" is not installed
     import QtMultimedia        // Qt 6.x
     ^
```

After, the configuration browser displays as expected.

**Comment by danieloneill** [comment]
I've done some initial work on testing for the presence of QtMultimedia in my integration branch which should hopefully help in this regard. In particular, it just loads a "stub" in case QtMultimedia fails to initialise for any reason.

For the moment I can only state that it works on my system, but after additional testing I'll push it to master for the next release.

As for the WebEngineView issue... it has so far been possible to build Twitch Overlay without having the requisite webengine QML components installed, which caused confusing issues at runtime as above. My new approach requires WebEngineView to be fully available at compile time. If it isn't, it just won't build, which is the Right Thing To Do.

Again, this is only on my integration branch until I can confirm it solves more problems than it creates (particularly on Windows), but I'll try to have it smoothed over for 1.3.
